name: Build ABCGuard.dylib
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build dylib
        run: |
          xcrun --sdk iphoneos swiftc -target arm64-apple-ios13.0 -emit-library -o ABCGuard.dylib -module-name ABCGuard \
          -Xcc -fobjc-arc \
          -framework UIKit -framework WebKit \
          ABCGuard.swift
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ABCGuard.dylib
          path: ABCGuard.dylib
